version: "2.4"

services:

  oathkeeper-proxy:
    ports:
      - 4455:4455
    command:
      serve proxy
    environment:
      - PORT=4455
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - ISSUER_URL=http://127.0.0.1:4455/
    volumes:
      - ./config/oathkeeper/jwks.json:/jwks.json
      - ./config/oathkeeper/rules.dev.json:/rules.json
      - ./config/oathkeeper/config.dev.yml:/.oathkeeper.yml
