version: "2.4"

services:

  user-service:
    build: 
      context: ../fyp-user-service-v3/.
      target: dev
    ports:
      - 50052:50052
    volumes:
      - ../fyp-user-service-v3:/app
    networks:
      - services
