version: "2.4"

services:

  hydra:
    ports:
      - 4444:4444
      - 4445:4445
    command:
      serve all --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - CORS_ENABLED=true
      - CORS_ALLOWED_METHODS=POST,GET,PUT,DELETE
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_LOGIN=http://127.0.0.1:3000
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - DSN=postgres://hydra:secret@hydra-db:5432/hydra?sslmode=disable
    networks:
      - proxy
