version: "2.4"

services:

  hydra:
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
    command:
      serve all --dangerous-force-http # Force HTTP for local development
    volumes:
      - ./config/hydra/config.dev.yml:/.hydra.yml
