hydra-migrate:
  image: oryd/hydra:v1.0.8
  command: ["migrate", "sql", "postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable"]
  environment:
    - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
