version: "2.4"

services:

  hydra:
    ports:
      - 4444:4444 # Public port
      - 4445:4445 # Admin port
      - 5555:5555 # Testing only. Creates an OAuth 2.0 client
    command:
      serve all --dangerous-force-http # Force HTTP for local development
    environment:
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_LOGIN=http://127.0.0.1:3000
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - DSN=postgres://hydra:secret@hydra-db:5432/hydra?sslmode=disable
