version: "2.4"

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command:
      migrate sql -e --yes
    environment:
      - HYDRA_SYSTEM_SECRET=youReallyNeedToChangeThis
      - DSN=postgres://hydra:secret@hydra-db:5432/hydra?sslmode=disable
    networks:
      - proxy
