version: "2.4"

services:

  hydra:
    image: oryd/hydra:v1.0.8

  hydra-db:
    image: postgres:12

  oathkeeper-proxy:
    image: oryd/oathkeeper:v0.32.0

  oathkeeper-api:
    image: oryd/oathkeeper:v0.32.0
