serve:
  api:
    cors:
      enabled: true
      debug: true
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE

  proxy:
    cors:
      enabled: true
      debug: true
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE

access_rules:
  repositories:
    - file:///rules.json

mutators:
  noop:
    enabled: true
  id_token:
    enabled: true
    config:
      issuer_url: http://127.0.0.1:4455/
      jwks_url: file:///jwks.json
      ttl: 525600m
      claims:
        '{"aud": ["vue"]}'

authorizers:
  allow:
    enabled: true

authenticators:
  noop:
    enabled: true  
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://hydra:4445/oauth2/introspect

log:
  level: debug
  format: json
